name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - "master"
  pull_request_target:
    branches:
    - "master"

jobs:
  test-dotnet:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            9.0.x
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
